#!/sbin/busybox sh

# dummy blocks extract
/sbin/busybox tar xvf /res/misc/dev.tar

# check boot rom
/sbin/busybox mount -t ext4 /dev/block/mmcblk0p10 /xdata
if [ "`/sbin/busybox grep secondary /xdata/boot.conf`" ]; then
  /sbin/busybox umount /xdata
  # secondary rom boot
  /sbin/busybox mount -t ext4 /dev/block/mmcblk0p12 /system
  if [ "`/sbin/busybox grep se.infra /system/build.prop`" ]; then
    /sbin/busybox umount /system
    exec /vendor/samsung/init.samsung secondary
  else
    /sbin/busybox umount /system
    exec /vendor/aosp/init.aosp secondary
  fi
else
  /sbin/busybox umount /xdata
  /sbin/busybox mount -t ext4 /dev/block/mmcblk0p9 /system
  # primary rom boot
  if [ "`/sbin/busybox grep se.infra /system/build.prop`" ]; then
    /sbin/busybox umount /system
    exec /vendor/samsung/init.samsung primary
  else
    /sbin/busybox umount /system
    exec /vendor/aosp/init.aosp primary
  fi
fi
