#!/sbin/busybox sh

PATH_=$PATH
export PATH=/sbin

# extract block device files
tar xvf /misc/dev.tar

mount -t proc proc /proc
#BUILD_TARGET=`cat /proc/sys/kernel/build_target`
BUILD_TARGET=2
RECOVERY_MODE=`grep -c bootmode=2 /proc/cmdline`
#umount /proc

if [ "$RECOVERY_MODE" = '1' ]; then
  # recovery mode
  sh /mbs/init.recovery.sh $BUILD_TARGET
else
  # normal mode
  sh /mbs/init.normal.sh $BUILD_TARGET
fi

# cleanup
rm -fr /dev/* /misc/dev.tar
# init start
mv /_init /init

export PATH=$PATH_
exec /init

