#!/sbin/busybox sh

# extract block device files
/sbin/busybox tar xvf /misc/dev.tar

/sbin/busybox mount -t proc proc /proc
BUILD_TARGET=`cat /proc/sys/kernel/build_target`
RECOVERY_MODE=`grep -c bootmode=2 /proc/cmdline`
/sbin/busybox umount /proc

if [ "$RECOVERY_MODE" = '1' ]; then
  # recovery mode
  /sbin/busybox sh /mbs/init.recovery.sh $BUILD_TARGET
else
  # mormal mode
  /sbin/busybox sh /mbs/init.common.sh $BUILD_TARGET
fi

# cleanup
/sbin/busybox rm -fr /dev/* /misc/dev.tar
# init start
/sbin/busybox mv /_init /init
exec /init

